# fly.toml app configuration file generated for paas-verification-tiny-nodejs on 2025-06-08T01:58:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


# 起動するためには
# fly apps create paas-verification-tiny-nodejs
# fly deploy
# 検証終わったら消す
# fly

app = 'paas-verification-tiny-nodejs'
primary_region = 'nrt'

[build]

[processes]
  app = "npm start"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
